# -*- coding: utf-8 -*-
"""Curso Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oYOvugjsyzmzxBAp79wxXXmgmuEBZXT9

Overview

Class: conjunto de objetos
properties: height of tree 
 methods: grow tree, remove

 metodos são ações que mudam propriedades

Curso Python #07 - Operadores Aritméticos

5//2=2 é uma divisão inteira

5%2=1 #o resultado será somente a sobra da divisão

127**(1/3) = 5.02 #o resultado é a raíz cúbica

'oi'*5 = 'oioioioioi' #multipica
```
# código
```
"""

nome = input("qual seu nome?")
print('prazer em te conhecer {:^20}!'.format(nome))  #fazer alinhamento do nome

n1 = int(input('numero1: '))
n2 = int(input('numero2: '))
soma = n1+n2
sub = n1- n2
div = n1//n2
pot = n1**n2
print(' a soma vale {}, \n a subtração vale {} e \n a divisão inteira vale {}'.format(soma, sub ,div))
print(' a potenciação vale {}'.format(pot))

#Desafio 005
n1 = int(input('escreva um número: '))
n0 = n1-1
n2 = n1+1
print("o antecessor é {} e o sucessor é {}".format(n0, n2))

#Desafio 006
n1 = int(input('insira um número'))
n2 = n1**2
n3 = n1**3
nraiz = n1**(1/2)

print('o dobro de {} é {}, o triplo é {} e a raiz quadrada é {}.'.format(n1,n2,n3,nraiz))

#Desafio 007
n1 = float(input('insira a primeira nota'))
n2 = float(input('insira a segunda nota'))
media = ((n1+n2)/2)
print('a média é {}'.format(media))

#Desafio 008
metro = float(input('insira sua altura'))
centimetro = metro*100
milimetro = centimetro*10
print('a altura é {}, em centrimetros é {} e em milimetros é {}'.format(metro, centimetro, milimetro))

#Desafio 009
n1 = int(input('insira um numero: '))
n2 = n1*2
n3 = n1*3
n4 = n1*4
n5 = n1*5
n6 = n1*6
n7 = n1*7
n8 = n1*8
n9 = n1*9
n10 = n1*10
print('1 x {} = {}'.format(n1,n1)) 
print('2 x {} = {}'.format(n1,n2)) 
print('3 x {} = {}'.format(n1,n3)) 
print('4 x {} = {}'.format(n1,n4)) 
print('5 x {} = {}'.format(n1,n5)) 
print('6 x {} = {}'.format(n1,n6)) 
print('7 x {} = {}'.format(n1,n7)) 
print('8 x {} = {}'.format(n1,n8)) 
print('9 x {} = {}'.format(n1,n9)) 
print('10 x {} = {}'.format(n1,n10))

#Desafio 10
real = float(input('quantos reais você tem na carteira?'))
dolar = real/4.12
print('você tem {} dolares'.format(dolar))

#Desafio 11
altura = float(input('insira a altura da parede'))
largura = float(input('insira a largura da parede'))
area = altura*largura
litros = area/2
print('o quarto tem {} e precisará de {} litros de tinta'.format(area, litros))

#Desafio 12
preco = float(input('insira o preço atual'))
desconto = preco*0.95
print('o preço atual é {}'.format(desconto))

#Desafio 13
atual = float(input('insira seu salário atual:'))
aumento = atual*1.15
print('seu salário atual é de {} reais'.format(aumento))

"""# Curso Python #08 - Utilizando Módulos"""